# -*- coding: utf-8 -*-
"""Generate 03 Foundation Micro/ipa/section-*/**/foundation-micro-authoring-pack.json (6 sections)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "03 Foundation Micro" / "ipa"


def rules(answer: int, triple: list):
    """
    triple: list of 3 dicts for wrong indices in order [first_wrong, second_wrong, third_wrong]
    where wrongs are sorted indices != answer. Each dict: error_tag, error_type, diagnosis, micro_lesson, retry_question dict.
    """
    wrong = [i for i in range(4) if i != answer]
    out = {}
    for wi, block in zip(wrong, triple):
        out[str(wi)] = block
    return out


def block(tag, etype, diag, lesson, rq, ropts, rans):
    return {
        "error_tag": tag,
        "error_type": etype,
        "diagnosis": diag,
        "micro_lesson": lesson,
        "retry_question": {"question": rq, "options": ropts, "answer": rans},
    }


def main_item(
    qid,
    topic,
    subtopic,
    concept_id,
    question,
    options,
    answer,
    rationale,
    skill,
    qtype,
    sec_slug,
    distractor_triple,
):
    return {
        "questionId": qid,
        "subject": "ipa",
        "topicId": None,
        "topic": topic,
        "subtopicId": None,
        "subtopic": subtopic,
        "difficulty": "easy",
        "skillType": skill,
        "questionType": qtype,
        "tags": ["foundation_micro", "ipa", sec_slug],
        "question": question,
        "options": options,
        "answer": answer,
        "rationale": rationale,
        "microLoop": {
            "concept_id": concept_id,
            "distractor_rules": rules(answer, distractor_triple),
        },
    }


def drill_item(qid, topic, subtopic, concept_id, question, options, answer, rationale, skill, qtype, sec_slug, err_tags):
    return {
        "questionId": qid,
        "subject": "ipa",
        "topicId": None,
        "topic": topic,
        "subtopicId": None,
        "subtopic": subtopic,
        "difficulty": "easy",
        "skillType": skill,
        "questionType": qtype,
        "tags": ["foundation_micro", "targeted_drill", "ipa", sec_slug],
        "question": question,
        "options": options,
        "answer": answer,
        "rationale": rationale,
        "microLoop": {
            "concept_id": concept_id,
            "drill_focus": {"source_error_tags": err_tags, "notes": "Penguatan satu konsep foundation."},
        },
    }


def std_blocks(concept_hint: str):
    """Generic triple for answer=0: wrong indices 1,2,3."""
    return [
        block(
            "miskonsepsi_utama",
            "concept",
            "Pilihan ini mencerminkan pemahaman konsep yang belum tepat untuk soal ini.",
            f"Kembali ke definisi inti «{concept_hint}», lalu cocokkan dengan kata kunci di soal.",
            "Manakah pernyataan yang paling netral dan sesuai definisi dasar konsep ini?",
            ["Definisi yang salah arah", "Definisi yang selaras buku teks sederhana", "Campuran dua konsep", "Jawaban tanpa bukti"],
            1,
        ),
        block(
            "terburu_buru",
            "careless",
            "Kemungkinan membaca opsi terlalu cepat sehingga melewatkan kata kunci penting.",
            "Baca ulang soal, garisbawahi kata kunci, lalu eliminasi opsi yang paling tidak relevan.",
            "Kata kunci pada soal biasanya menuntun ke satu konsep utama. Langkah awal yang baik adalah ...",
            ["Langsung menebak huruf opsi", "Mengidentifikasi konsep yang ditanya", "Menghitung tanpa konteks", "Mengabaikan semua opsi"],
            1,
        ),
        block(
            "campur_konsep_lain",
            "strategy",
            "Kamu mungkin memakai konsep dari topik lain yang mirip istilahnya.",
            "Tetapkan dulu topik soal, baru pilih hukum/definisi yang dipakai di topik itu saja.",
            "Jika soal jelas tentang satu sistem organ, hindari menjawab dengan konsep ...",
            ["Organ lain yang tidak disebut", "Mekanisme yang sama pada organ yang dimaksud", "Istilah umum yang tepat", "Data yang konsisten"],
            1,
        ),
    ]


def write(rel_dir: str, pack: dict):
    d = OUT / rel_dir
    d.mkdir(parents=True, exist_ok=True)
    fp = d / "foundation-micro-authoring-pack.json"
    fp.write_text(json.dumps(pack, ensure_ascii=False, indent=2), encoding="utf-8")
    print("Wrote", fp)


# ---------- Section 1 ----------
sec1 = "section-1/keterampilan-proses-sains"
pack1 = {
    "authoring_request": {
        "mode": "foundation_micro",
        "subject": "ipa",
        "topic": "Sistem Kehidupan",
        "subtopic": "Fotosintesis & respirasi tumbuhan",
        "grade_band": "sd_4_6_foundation",
        "student_goal": "Menguasai variabel percobaan, urutan metode ilmiah, dan pembacaan data sederhana (Study Guide Section 1).",
        "requested_micro_concept_count": 3,
        "requested_main_questions_per_concept": 3,
        "requested_drill_questions_per_concept": 5,
        "language": "id",
    },
    "micro_concepts": [
        {
            "concept_id": "variabel_bebas_terikat_kontrol",
            "concept_name": "Variabel bebas, terikat, kontrol",
            "concept_description": "Membedakan faktor yang diubah, diukur, dan dijaga tetap.",
            "topic": "Sistem Kehidupan",
            "subtopic": "Fotosintesis & respirasi tumbuhan",
            "target_error_tags": ["campur_variabel", "kontrol_terlewat", "terikat_dianggap_bebas"],
        },
        {
            "concept_id": "urutan_metode_ilmiah_ringkas",
            "concept_name": "Alur metode ilmiah",
            "concept_description": "Urutan observasi, pertanyaan, hipotesis, percobaan, analisis, kesimpulan.",
            "topic": "Materi & Perubahannya",
            "subtopic": "Perubahan fisika vs kimia",
            "target_error_tags": ["langkah_terbalik", "kesimpulan_tanpa_data"],
        },
        {
            "concept_id": "satuan_dan_label_data",
            "concept_name": "Satuan dan label data",
            "concept_description": "Membaca satuan dan menjumlahkan data sederhana pada tabel ringkas.",
            "topic": "Bumi & Alam Semesta",
            "subtopic": "Cuaca & iklim",
            "target_error_tags": ["abaikan_satuan", "salah_jumlah"],
        },
    ],
    "main_questions": [
        main_item(
            "ipa-s1-main-01",
            "Sistem Kehidupan",
            "Fotosintesis & respirasi tumbuhan",
            "variabel_bebas_terikat_kontrol",
            "Percobaan: «Apakah lama penyinaran memengaruhi tinggi kecambah?» Variabel **terikat** yang paling tepat adalah ...",
            ["Tinggi kecambah yang diukur", "Lama penyinaran per hari", "Jenis air penyiraman", "Warna pot"],
            0,
            "Terikat = hasil yang diukur: tinggi kecambah.",
            "experiment_interpretation",
            "experiment_interpretation",
            sec1,
            [
                block(
                    "terikat_dianggap_bebas",
                    "concept",
                    "Kamu memilih faktor yang sengaja diubah peneliti; itu variabel bebas.",
                    "Variabel bebas = yang diatur; variabel terikat = hasil pengukuran.",
                    "Dalam percobaan «pengaruh suhu air terhadap waktu larut gula», yang diukur sebagai hasil utama biasanya adalah ...",
                    ["Suhu air", "Waktu larut gula", "Warna gelas", "Merek kompor"],
                    1,
                ),
                block(
                    "campur_variabel",
                    "concept",
                    "Faktor ini sebaiknya dikontrol agar sama, bukan sebagai jawaban «terikat» pada fokus soal.",
                    "Terikat harus selaras dengan pertanyaan penelitian: apa jawaban numerik/kualitatif yang dicatat?",
                    "Variabel terikat pada percobaan tumbuhan di atas adalah besaran yang ...",
                    ["Dijaga tetap sama", "Dicatat sebagai respons terhadap cahaya", "Tidak diukur", "Hanya perkiraan"],
                    1,
                ),
                block(
                    "kontrol_terlewat",
                    "strategy",
                    "Ini lebih mirip variabel kontrol atau faktor samping, bukan jawaban terikat utama.",
                    "Tanyakan: «Apa yang menjadi jawaban data utama?» untuk memilih terikat.",
                    "Yang dijaga sama antar kelompok agar adil dalam percobaan tadi termasuk ...",
                    ["Tinggi akhir saja", "Jenis biji, volume media, dan penyiraman yang setara", "Lama cahaya saja", "Warna daun"],
                    1,
                ),
            ],
        ),
        main_item(
            "ipa-s1-main-02",
            "Sistem Kehidupan",
            "Fotosintesis & respirasi tumbuhan",
            "variabel_bebas_terikat_kontrol",
            "Pada percobaan yang sama, variabel **bebas** yang paling tepat adalah ...",
            ["Lama penyinaran per hari", "Tinggi kecambah", "Kelembapan ruangan yang tidak diatur", "Warna cat pot"],
            0,
            "Bebas = yang sengaja diubah: lama cahaya.",
            "experiment_interpretation",
            "experiment_interpretation",
            sec1,
            std_blocks("variabel bebas"),
        ),
        main_item(
            "ipa-s1-main-03",
            "Sistem Kehidupan",
            "Fotosintesis & respirasi tumbuhan",
            "variabel_bebas_terikat_kontrol",
            "Variabel **kontrol** yang paling penting agar perbandingan lama cahaya adil adalah ...",
            [
                "Jenis biji, suhu ruangan, dan volume air penyiraman yang sama",
                "Tinggi kecambah akhir",
                "Lama penyinaran",
                "Jumlah daun pertama kali terbuka"
            ],
            0,
            "Kontrol menjaga faktor pengganggu tetap: bibit, air, suhu ruang setara.",
            "experiment_interpretation",
            "experiment_interpretation",
            sec1,
            std_blocks("variabel kontrol"),
        ),
        main_item(
            "ipa-s1-main-04",
            "Materi & Perubahannya",
            "Perubahan fisika vs kimia",
            "urutan_metode_ilmiah_ringkas",
            "Setelah mengamati gejala, langkah metode ilmiah yang lazim **berikutnya** adalah ...",
            [
                "Merumuskan pertanyaan atau masalah",
                "Langsung menulis kesimpulan akhir",
                "Membeli alat tanpa tujuan",
                "Mengabaikan pengukuran"
            ],
            0,
            "Setelah observasi: rumuskan pertanyaan sebelum hipotesis dan percobaan.",
            "understanding",
            "concept_check",
            sec1,
            std_blocks("metode ilmiah"),
        ),
        main_item(
            "ipa-s1-main-05",
            "Materi & Perubahannya",
            "Perubahan fisika vs kimia",
            "urutan_metode_ilmiah_ringkas",
            "**Hipotesis** berperan sebagai ...",
            [
                "Dugaan terarah yang akan diuji dengan data",
                "Hasil final yang tidak boleh salah",
                "Nama alat ukur",
                "Langkah terakhir sebelum publikasi"
            ],
            0,
            "Hipotesis = jawaban sementara yang diuji.",
            "recall",
            "direct",
            sec1,
            std_blocks("hipotesis"),
        ),
        main_item(
            "ipa-s1-main-06",
            "Materi & Perubahannya",
            "Perubahan fisika vs kimia",
            "urutan_metode_ilmiah_ringkas",
            "Urutan inti yang **benar** adalah ...",
            [
                "Observasi → pertanyaan → hipotesis → percobaan → analisis → kesimpulan",
                "Kesimpulan → hipotesis → observasi",
                "Percobaan → kesimpulan → pertanyaan",
                "Hipotesis → kesimpulan tanpa data"
            ],
            0,
            "Alur dimulai dari pengamatan, diakhiri kesimpulan berbasis data.",
            "understanding",
            "concept_check",
            sec1,
            std_blocks("urutan metode ilmiah"),
        ),
        main_item(
            "ipa-s1-main-07",
            "Bumi & Alam Semesta",
            "Cuaca & iklim",
            "satuan_dan_label_data",
            "Data curah hujan lima hari (mm): 2, 0, 10, 5, 3. Total lima hari adalah ...",
            ["20 mm", "21 mm", "15 mm", "30 mm"],
            0,
            "2+0+10+5+3 = 20 mm.",
            "application",
            "data_interpretation",
            sec1,
            [
                block("salah_jumlah", "careless", "Jumlah penjumlahan belum tepat.", "Jumlahkan ulang perlahan termasuk hari 0 mm.", "1 + 2 + 3 = ...", ["5", "6", "7", "4"], 1),
                block("abaikan_satuan", "concept", "Satuan mm ikut membentuk makna besaran hujan.", "Tetap tulis satuan yang sama saat menjumlahkan.", "3 cm + 2 cm = ...", ["5 cm", "6 cm", "32 cm", "1 cm"], 0),
                block("salah_jumlah", "strategy", "Mungkin ada suku yang terlewat atau terhitung dua kali.", "Cek lima suku satu per satu.", "10 + 5 = ...", ["14", "15", "16", "50"], 1),
            ],
        ),
        main_item(
            "ipa-s1-main-08",
            "Bumi & Alam Semesta",
            "Cuaca & iklim",
            "satuan_dan_label_data",
            "Sumbu vertikal bertuliskan «suhu (°C)». Simbol **°C** menunjukkan ...",
            ["Satuan suhu Celsius", "Satuan panjang", "Satuan massa", "Satuan tekanan"],
            0,
            "°C adalah derajat Celsius untuk suhu.",
            "recall",
            "data_interpretation",
            sec1,
            std_blocks("sumbu grafik"),
        ),
        main_item(
            "ipa-s1-main-09",
            "Bumi & Alam Semesta",
            "Cuaca & iklim",
            "satuan_dan_label_data",
            "Grafik memplot «waktu (jam)» di sumbu X dan «suhu (°C)» di sumbu Y. Grafik itu menunjukkan ...",
            ["Bagaimana suhu berubah terhadap waktu", "Massa benda terhadap volume", "Jarak terhadap gaya", "Banyaknya predator"],
            0,
            "Judul sumbu X dan Y menentukan pasangan variabel yang dibandingkan.",
            "understanding",
            "data_interpretation",
            sec1,
            std_blocks("label sumbu"),
        ),
    ],
    "drill_questions": [],
}
# drills s1
d = 0
for cid, top, sub, pairs in [
    (
        "variabel_bebas_terikat_kontrol",
        "Sistem Kehidupan",
        "Fotosintesis & respirasi tumbuhan",
        [
            ("Yang diukur sebagai terikat pada «pengaruh jarak lampu terhadap suhu air di bawahnya»?", ["Jarak lampu", "Suhu air", "Warna air", "Merek stopwatch"], 1),
            ("Variabel bebas pada soal di atas adalah ...", ["Suhu air", "Jarak lampu ke permukaan air", "Volume air jika sama semua", "Jenis termometer"], 1),
            ("Agar adil, volume air dan waktu pemanasan sebaiknya ...", ["Berbeda bebas", "Sama (kontrol)", "Hanya satu kelompok", "Tak perlu dicatat"], 1),
            ("Hasil utama yang dicatat biasanya berkaitan erat dengan ...", ["Pertanyaan penelitian", "Warna meja", "Nama peneliti", "Hari libur"], 0),
            ("Kontrol membantu ...", ["Membuat percobaan tidak terukur", "Mengurangi pengaruh faktor pengganggu", "Menghapus hipotesis", "Menambah variabel bebas"], 1),
        ],
    ),
    (
        "urutan_metode_ilmiah_ringkas",
        "Materi & Perubahannya",
        "Perubahan fisika vs kimia",
        [
            ("Langkah pertama yang umum adalah ...", ["Hipotesis", "Observasi", "Kesimpulan", "Percobaan"], 1),
            ("Sebelum percobaan, biasanya ada ...", ["Kesimpulan", "Hipotesis", "Penjualan alat", "Laporan akhir"], 1),
            ("Analisis data digunakan untuk ...", ["Menghapus data", "Mencari pola mendukung kesimpulan", "Mengganti pertanyaan", "Menghindari grafik"], 1),
            ("Kesimpulan harus ...", ["Melawan data", "Selaras bukti", "Tidak perlu alasan", "Hanya opini"], 1),
            ("«Mengulang percobaan» membantu ...", ["Memperburuk data", "Mengurangi kebetulan sekali ukur", "Menghapus variabel", "Menghilangkan satuan"], 1),
        ],
    ),
    (
        "satuan_dan_label_data",
        "Bumi & Alam Semesta",
        "Cuaca & iklim",
        [
            ("1 + 2 + 3 = ...", ["5", "6", "7", "4"], 1),
            ("Sumbu «t (jam)» artinya ...", ["Massa jam", "Waktu dalam jam", "Suhu", "Jarak"], 1),
            ("Tanpa satuan, angka 10 pada data bisa bermakna ...", ["Jelas tanpa konteks", "Ambigu", "Selalu meter", "Selalu detik"], 1),
            ("4 mm + 6 mm = ...", ["10 mm", "24 mm", "2 mm", "1 mm"], 0),
            ("Judul tabel membantu pembaca ...", ["Menghapus kolom", "Tahu apa yang diukur", "Menghindari baris", "Menghilangkan sumbu"], 1),
        ],
    ),
]:
    for q, o, a in pairs:
        d += 1
        pack1["drill_questions"].append(
            drill_item(f"ipa-s1-drill-{d:02d}", top, sub, cid, q, o, a, "Drill ringkas.", "understanding", "direct", sec1, ["campur_variabel"])
        )

write(sec1, pack1)

# ---------- Section 2 ----------
sec2 = "section-2/sistem-kehidupan-dan-ekosistem"
pack2 = {
    "authoring_request": {
        "mode": "foundation_micro",
        "subject": "ipa",
        "topic": "Sistem Kehidupan",
        "subtopic": "Fotosintesis & respirasi tumbuhan",
        "grade_band": "sd_4_6_foundation",
        "student_goal": "Konsep organ–sistem, fotosintesis, peredaran darah, daur hidup, dan rantai makanan (Section 2).",
        "requested_micro_concept_count": 3,
        "requested_main_questions_per_concept": 3,
        "requested_drill_questions_per_concept": 5,
        "language": "id",
    },
    "micro_concepts": [
        {
            "concept_id": "fotosintesis_gas_dan_peran",
            "concept_name": "Fotosintesis: gas dan peran produsen",
            "concept_description": "CO2 masuk, O2 keluar pada fotosintesis; daun sebagai lokasi utama.",
            "topic": "Sistem Kehidupan",
            "subtopic": "Fotosintesis & respirasi tumbuhan",
            "target_error_tags": ["balik_gas", "lupa_produsen"],
        },
        {
            "concept_id": "peredaran_darahalur_kecil_besar",
            "concept_name": "Alur peredaran darah kecil dan besar",
            "concept_description": "Darah ke paru dan kembali vs darah ke tubuh.",
            "topic": "Sistem Kehidupan",
            "subtopic": "Sistem peredaran darah",
            "target_error_tags": ["campur_alur", "paru_dianggap_tubuh"],
        },
        {
            "concept_id": "rantai_makanan_peran",
            "concept_name": "Produsen, konsumen, pengurai",
            "concept_description": "Arah energi dan peran dalam rantai makanan.",
            "topic": "Ekologi & Pewarisan",
            "subtopic": "Rantai makanan & jaring-jaring makanan",
            "target_error_tags": ["arah_energi_terbalik", "produsen_salah"],
        },
    ],
    "main_questions": [
        main_item(
            "ipa-s2-main-01",
            "Sistem Kehidupan",
            "Fotosintesis & respirasi tumbuhan",
            "fotosintesis_gas_dan_peran",
            "Pada fotosintesis, gas yang **banyak dilepas** ke udara oleh tumbuhan hijau pada siang terang adalah ...",
            ["Oksigen (O2)", "Karbon dioksida (CO2)", "Nitrogen murni", "Hidrogen bebas"],
            0,
            "Fotosintesis melepaskan O2 sebagai hasil samping fotolisis air dan reduksi karbon.",
            "concept_understanding",
            "concept_check",
            sec2,
            [
                block(
                    "balik_gas",
                    "concept",
                    "CO2 banyak diserap, bukan dilepas dominan saat fotosintesis aktif.",
                    "Ingat skema sederhana: CO2 masuk, O2 keluar pada fotosintesis.",
                    "Gas yang diserap tumbuhan untuk fotosintesis termasuk ...",
                    ["O2 saja", "CO2", "N2 saja", "He"],
                    1,
                ),
                block("lupa_produsen", "strategy", "Pilihan gas yang tidak relevan dengan reaksi fotosintesis.", "Fokus pada pasangan CO2–O2 pada materi fotosintesis.", "Produsen dalam rantai makanan umumnya adalah ...", ["Karnivora", "Tumbuhan hijau", "Jamur pengurai", "Awan"], 1),
                block("balik_gas", "careless", "Nitrogen dominan di udara tetapi bukan fokus gas fotosintesis.", "Soal menanyakan hasil gas pada proses fotosintesis.", "Yang dihasilkan tumbuhan pada fotosintesis selain glukosa meliputi ...", ["O2", "CO2 murni saja", "Asam sulfat", "Debu"], 0),
            ],
        ),
        main_item(
            "ipa-s2-main-02",
            "Sistem Kehidupan",
            "Fotosintesis & respirasi tumbuhan",
            "fotosintesis_gas_dan_peran",
            "Tempat utama fotosintesis pada tumbuhan darat biasanya adalah ...",
            ["Daun (terutama jaringan berkloroplas)", "Akar", "Batang kayu mati", "Bunga saja"],
            0,
            "Kloroplas terkonsentrasi di daun.",
            "recall",
            "direct",
            sec2,
            std_blocks("fotosintesis"),
        ),
        main_item(
            "ipa-s2-main-03",
            "Sistem Kehidupan",
            "Fotosintesis & respirasi tumbuhan",
            "fotosintesis_gas_dan_peran",
            "Tumbuhan hijau disebut **produsen** karena ...",
            [
                "Mampu membuat makanan organik dari zat anorganik dengan energi cahaya",
                "Hanya memakan serangga",
                "Tidak memerlukan air",
                "Hanya hidup di air"
            ],
            0,
            "Produsen membuat makanan sendiri (autotrof).",
            "understanding",
            "concept_check",
            sec2,
            std_blocks("produsen"),
        ),
        main_item(
            "ipa-s2-main-04",
            "Sistem Kehidupan",
            "Sistem peredaran darah",
            "peredaran_darahalur_kecil_besar",
            "**Peredaran kecil** (pulmonal) menghubungkan ...",
            ["Jantung ↔ paru-paru", "Jantung ↔ seluruh tubuh", "Hati ↔ lambung", "Ginjal ↔ otak saja"],
            0,
            "Peredaran kecil: pompa darah menuju paru dan kembali untuk pertukaran gas.",
            "concept_understanding",
            "concept_check",
            sec2,
            std_blocks("peredaran kecil"),
        ),
        main_item(
            "ipa-s2-main-05",
            "Sistem Kehidupan",
            "Sistem peredaran darah",
            "peredaran_darahalur_kecil_besar",
            "**Peredaran besar** (sistemik) menghubungkan ...",
            ["Jantung ↔ seluruh tubuh", "Jantung ↔ paru saja", "Paru ↔ hati", "Lambung ↔ usus saja"],
            0,
            "Peredaran besar mendistribusikan darah kaya oksigen ke organ.",
            "concept_understanding",
            "concept_check",
            sec2,
            std_blocks("peredaran besar"),
        ),
        main_item(
            "ipa-s2-main-06",
            "Sistem Kehidupan",
            "Sistem peredaran darah",
            "peredaran_darahalur_kecil_besar",
            "Pembuluh yang membawa darah **keluar** dari jantung menuju tubuh (umumnya) termasuk pola ...",
            ["Arteri sistemik dari bilik kiri", "Vena pulmonal", "Kapiler di paru saja", "Limpfe"],
            0,
            "Bilik kiri memompa ke arteri menuju tubuh (sistemik).",
            "application",
            "direct",
            sec2,
            std_blocks("arteri vena"),
        ),
        main_item(
            "ipa-s2-main-07",
            "Ekologi & Pewarisan",
            "Rantai makanan & jaring-jaring makanan",
            "rantai_makanan_peran",
            "Pada rantai makanan «rumput → kelinci → ular», kelinci berperan sebagai ...",
            ["Konsumen primer", "Produsen", "Pengurai", "Produsen sekunder"],
            0,
            "Herbivora memakan produsen = konsumen primer.",
            "understanding",
            "concept_check",
            sec2,
            std_blocks("rantai makanan"),
        ),
        main_item(
            "ipa-s2-main-08",
            "Ekologi & Pewarisan",
            "Rantai makanan & jaring-jaring makanan",
            "rantai_makanan_peran",
            "Arah aliran energi klasik dalam rantai makanan adalah ...",
            ["Produsen → konsumen → pengurai", "Pengurai → produsen", "Konsumen → produsen", "Konsumen → konsumen tanpa produsen"],
            0,
            "Energi masuk dari produsen lalu ke konsumen, akhirnya ke pengurai.",
            "concept_understanding",
            "concept_check",
            sec2,
            std_blocks("aliran energi"),
        ),
        main_item(
            "ipa-s2-main-09",
            "Ekologi & Pewarisan",
            "Rantai makanan & jaring-jaring makanan",
            "rantai_makanan_peran",
            "Jamur dan bakteri pengurai berperan utama dalam ...",
            [
                "Menguraikan sisa organik sehingga zat bisa kembali ke siklus nutrien",
                "Membuat makanan dengan fotosintesis",
                "Memompa darah",
                "Menghasilkan O2 primer di laut dalam"
            ],
            0,
            "Pengurai memecah materi organik.",
            "understanding",
            "direct",
            sec2,
            std_blocks("pengurai"),
        ),
    ],
    "drill_questions": [],
}
d = 0
for cid, top, sub, pairs in [
    (
        "fotosintesis_gas_dan_peran",
        "Sistem Kehidupan",
        "Fotosintesis & respirasi tumbuhan",
        [
            ("Gas yang dipakai tumbuhan sebagai sumber karbon untuk fotosintesis termasuk ...", ["O2", "CO2", "N2", "He"], 1),
            ("O2 pada fotosintesis cenderung ...", ["Diserap dominan", "Dilepas", "Tidak terlibat", "Menjadi besi"], 1),
            ("Produsen memulai rantai karena ...", ["Memakan predator", "Menyimpan energi dalam senyawa organik", "Tidak butuh air", "Hidup tanpa sel"], 1),
            ("Daun berperan karena mengandung banyak ...", ["Kloroplas", "Tulang besi", "Asam kuat", "Minyak bumi"], 0),
            ("Fotosintesis butuh energi dari ...", ["Cahaya", "Garam dapur saja", "Es batu", "Magnet"], 0),
        ],
    ),
    (
        "peredaran_darahalur_kecil_besar",
        "Sistem Kehidupan",
        "Sistem peredaran darah",
        [
            ("Pertukaran gas CO2–O2 di paru terjadi di ...", ["Jantung", "Alveolus", "Lambung", "Hati"], 1),
            ("Peredaran kecil terkait erat dengan ...", ["Pencernaan", "Paru-paru", "Pendengaran", "Pengecap"], 1),
            ("Jantung berperan sebagai ...", ["Pompa", "Filter ginjal saja", "Pencernaan lemak", "Produksi hormon tiroid saja"], 0),
            ("Vena umumnya membawa darah ...", ["Keluar jantung", "Kembali ke jantung", "Hanya ke otak", "Tak ada pola"], 1),
            ("Arteri umumnya membawa darah ...", ["Dari jantung ke organ", "Dari paru ke lambung", "Dari kulit ke mata saja", "Statis"], 0),
        ],
    ),
    (
        "rantai_makanan_peran",
        "Ekologi & Pewarisan",
        "Rantai makanan & jaring-jaring makanan",
        [
            ("Rumput dalam rantai biasanya ...", ["Konsumen", "Produsen", "Pengurai", "Top predator"], 1),
            ("Ular pemakan kelinci umumnya ...", ["Produsen", "Konsumen sekunder atau tertier", "Pengurai primer", "Abiotik"], 1),
            ("Tanpa produsen, rantai akan ...", ["Lebih kuat", "Kehilangan sumber energi masuk", "Tetap sama", "Hanya bertambah pengurai"], 1),
            ("Pengurai mendapat energi dari ...", ["Cahaya matahari langsung", "Sisa organik", "Oksigen murni", "Batu"], 1),
            ("Jaring-jaring makanan muncul karena ...", ["Hanya satu rantai", "Banyak rantai saling hubung", "Tidak ada predator", "Tidak ada produsen"], 1),
        ],
    ),
]:
    for q, o, a in pairs:
        d += 1
        pack2["drill_questions"].append(
            drill_item(f"ipa-s2-drill-{d:02d}", top, sub, cid, q, o, a, "Drill.", "understanding", "direct", sec2, ["balik_gas"])
        )

write(sec2, pack2)

# ---------- Section 3 ----------
sec3 = "section-3/materi-gaya-kalor-cahaya-bunyi"
pack3 = {
    "authoring_request": {
        "mode": "foundation_micro",
        "subject": "ipa",
        "topic": "Materi & Perubahannya",
        "subtopic": "Perubahan fisika vs kimia",
        "grade_band": "sd_4_6_foundation",
        "student_goal": "Materi, perubahan fisika–kimia, gaya, kalor, cahaya, bunyi (Section 3).",
        "requested_micro_concept_count": 3,
        "requested_main_questions_per_concept": 3,
        "requested_drill_questions_per_concept": 5,
        "language": "id",
    },
    "micro_concepts": [
        {
            "concept_id": "fisika_vs_kimia",
            "concept_name": "Perubahan fisika vs kimia",
            "concept_description": "Ada atau tidaknya zat baru.",
            "topic": "Materi & Perubahannya",
            "subtopic": "Perubahan fisika vs kimia",
            "target_error_tags": ["campur_fisika_kimia", "lupa_zat_baru"],
        },
        {
            "concept_id": "gaya_dan_efek_benda",
            "concept_name": "Gaya mengubah gerak atau bentuk",
            "concept_description": "Gaya sebagai tarik/dorong; dampak pada gerak dan bentuk.",
            "topic": "Gerak, Gaya & Energi",
            "subtopic": "Gaya & pengaruhnya terhadap benda",
            "target_error_tags": ["abaikan_gaya", "gerak_tanpa_gaya"],
        },
        {
            "concept_id": "perpindahan_panas",
            "concept_name": "Konduksi, konveksi, radiasi",
            "concept_description": "Mekanisme perpindahan kalor sederhana.",
            "topic": "Gerak, Gaya & Energi",
            "subtopic": "Kalor & perpindahan panas",
            "target_error_tags": ["campur_mekanisme", "radiasi_dianggap_konduksi"],
        },
    ],
    "main_questions": [
        main_item(
            "ipa-s3-main-01",
            "Materi & Perubahannya",
            "Perubahan fisika vs kimia",
            "fisika_vs_kimia",
            "Es mencair menjadi air pada suhu tetap tekanan: peristiwa ini termasuk ...",
            ["Perubahan fisika (wujud berubah, zat tetap H2O)", "Perubahan kimia (zat baru)", "Reaksi pembakaran", "Fusi inti"],
            0,
            "Mencair = perubahan wujud, masih air.",
            "concept_understanding",
            "concept_check",
            sec3,
            std_blocks("fisika vs kimia"),
        ),
        main_item(
            "ipa-s3-main-02",
            "Materi & Perubahannya",
            "Perubahan fisika vs kimia",
            "fisika_vs_kimia",
            "Besi berkarat membentuk oksida besi. Ini termasuk ...",
            ["Perubahan kimia (zat baru)", "Perubahan fisika saja", "Pemisahan campuran", "Penguapan saja"],
            0,
            "Karat = zat baru (oksida).",
            "understanding",
            "concept_check",
            sec3,
            std_blocks("karat"),
        ),
        main_item(
            "ipa-s3-main-03",
            "Materi & Perubahannya",
            "Perubahan fisika vs kimia",
            "fisika_vs_kimia",
            "Gula larut dalam air membentuk larutan. Tanpa reaksi baru yang mengubah identitas molekul gula (model SD sederhana), ini sering diklasifikasikan sebagai ...",
            ["Perubahan fisika (larutan homogen, mudah dipikirkan sebagai pencampuran)", "Pembakaran", "Karat", "Fotosintesis"],
            0,
            "Level SD: melarutkan sering dikelompokkan fisika/pencampuran vs kimia yang jelas zat baru.",
            "understanding",
            "concept_check",
            sec3,
            std_blocks("larutan"),
        ),
        main_item(
            "ipa-s3-main-04",
            "Gerak, Gaya & Energi",
            "Gaya & pengaruhnya terhadap benda",
            "gaya_dan_efek_benda",
            "Rem sepeda memperlambat roda karena ada ...",
            ["Gaya gesek antara rem dan velg/roda", "Gaya magnet pada rantai", "Gaya gravitasi nol", "Gaya archimedes"],
            0,
            "Gesekan kinetik rem melawan gerak relatif.",
            "application",
            "direct",
            sec3,
            std_blocks("gesek"),
        ),
        main_item(
            "ipa-s3-main-05",
            "Gerak, Gaya & Energi",
            "Gaya & pengaruhnya terhadap benda",
            "gaya_dan_efek_benda",
            "Memutar spons basah memeras air keluar: gaya pemain paling relevan adalah ...",
            ["Gaya tekan/tarik yang mengubah bentuk spons", "Gaya gravitasi bulan", "Gaya Coulomb antar planet", "Gaya buoyancy saja tanpa kontak"],
            0,
            "Tekanan tangan mengubah bentuk dan mengeluarkan air.",
            "understanding",
            "concept_check",
            sec3,
            std_blocks("bentuk"),
        ),
        main_item(
            "ipa-s3-main-06",
            "Gerak, Gaya & Energi",
            "Gaya & pengaruhnya terhadap benda",
            "gaya_dan_efek_benda",
            "Benda diam mulai bergerak jika resultan gaya ...",
            ["Tidak nol (ada gaya neto)", "Selalu nol", "Hanya vertikal", "Tak bergantung massa"],
            0,
            "Hukum Newton I/II level SD: resultan gaya memengaruhi gerak.",
            "concept_understanding",
            "concept_check",
            sec3,
            std_blocks("resultan gaya"),
        ),
        main_item(
            "ipa-s3-main-07",
            "Gerak, Gaya & Energi",
            "Kalor & perpindahan panas",
            "perpindahan_panas",
            "Memanaskan sendok logam ujungnya di api, pegangan tetap lama terasa panas karena ...",
            ["Konduksi panas sepanjang logam", "Hanya radiasi tanpa kontak", "Konveksi di dalam kayu pegangan", "Pembekuan"],
            0,
            "Logam konduktor: panas merambat.",
            "understanding",
            "concept_check",
            sec3,
            std_blocks("konduksi"),
        ),
        main_item(
            "ipa-s3-main-08",
            "Gerak, Gaya & Energi",
            "Kalor & perpindahan panas",
            "perpindahan_panas",
            "Air mendidih di panci, aliran naik-turun membentuk pola arus: ini perpindahan panas utama lewat ...",
            ["Konveksi pada fluida", "Konduksi saja dalam logam tanpa gerak fluida", "Radiasi vakum", "Hantaran nol"],
            0,
            "Fluida panas naik, dingin turun: konveksi.",
            "understanding",
            "concept_check",
            sec3,
            std_blocks("konveksi"),
        ),
        main_item(
            "ipa-s3-main-09",
            "Gerak, Gaya & Energi",
            "Kalor & perpindahan panas",
            "perpindahan_panas",
            "Merasa hangat pada wajah saat berada di dekat api unggun meski tidak menyentuh api: perpindahan panas dominan adalah ...",
            ["Radiasi", "Konduksi melalui tongkat jauh", "Konveksi dalam logam wajah", "Pembekuan"],
            0,
            "Radiasi bisa melintasi ruang udara.",
            "understanding",
            "concept_check",
            sec3,
            std_blocks("radiasi"),
        ),
    ],
    "drill_questions": [],
}
# fix main-09 concept to cahaya - actually it's heat radiation, use Kalor subtopic - already Kalor. Change concept_id for last main to radiasi_termal - but micro_concepts doesn't have it. Keep perpindahan_panas for all three kalor mains - main-09 is radiasi - same concept_id OK.

d = 0
for cid, top, sub, pairs in [
    (
        "fisika_vs_kimia",
        "Materi & Perubahannya",
        "Perubahan fisika vs kimia",
        [
            ("Membakar kertas menghasilkan abu: cenderung ...", ["Fisika", "Kimia", "Tidak berubah", "Hanya penguapan"], 1),
            ("Memotong kertas: bentuk berubah, zat kertas tetap → ...", ["Kimia", "Fisika", "Nuklir", "Biologi evolusi"], 1),
            ("Tanda perubahan kimia sering termasuk ...", ["Tetap sama warna", "Bau/zat baru", "Suhu tetap selalu", "Tidak ada energi"], 1),
            ("Menguapnya air murni umumnya ...", ["Fisika", "Kimia selalu", "Fusi inti", "Korosi"], 0),
            ("Karat pada besi menandakan ...", ["Zat baru terbentuk", "Tidak ada reaksi", "Hanya pemuaian", "Hanya perubahan wujud air"], 0),
        ],
    ),
    (
        "gaya_dan_efek_benda",
        "Gerak, Gaya & Energi",
        "Gaya & pengaruhnya terhadap benda",
        [
            ("Gaya gravitasi Bumi pada benda arahnya umumnya ...", ["Ke pusat bumi (ke bawah)", "Ke atas", "Mendatar saja", "Acak"], 0),
            ("Gaya normal pada benda di meja arahnya ...", ["Tegak lurus permukaan penyangga", "Selalu ke bawah pusat bumi", "Sejajar meja saja", "Nol selalu"], 0),
            ("Magnet menarik klip besi: gaya ...", ["Magnetik", "Hanya gravitasi", "Hanya berat nol", "Bunyi"], 0),
            ("Gaya bisa mengubah ...", ["Hanya warna cat", "Gerak atau bentuk benda", "Hanya suhu inti bumi", "Hanya massa inti"], 1),
            ("Resultan nol pada benda bisa berarti ...", ["Pasti tidak ada gaya sama sekali", "Benda diam atau GLB konstan (model sederhana)", "Selalu dipercepat", "Selalu berputar"], 1),
        ],
    ),
    (
        "perpindahan_panas",
        "Gerak, Gaya & Energi",
        "Kalor & perpindahan panas",
        [
            ("Logam di kompor cepat panas di ujung: ...", ["Isolator", "Konduktor", "Vakum", "Resistor arus"], 1),
            ("Arus panas pada air mendidih yang naik: ...", ["Konveksi", "Hanya radiasi", "Hanya konduksi vakum", "Listrik"], 0),
            ("Matahari ke bumi melewat ruang hampa: ...", ["Konduksi", "Radiasi", "Konveksi zat padat", "Suara"], 1),
            ("Termos berisi isolator mengurangi ...", ["Perpindahan panas", "Massa air nol", "Gravitasi", "Cahaya selalu"], 0),
            ("Pemuaian logam dipanaskan: ...", ["Memendek pasti", "Cenderung memanjang/membesar", "Menghilang", "Menjadi cair selalu"], 1),
        ],
    ),
]:
    for q, o, a in pairs:
        d += 1
        pack3["drill_questions"].append(
            drill_item(f"ipa-s3-drill-{d:02d}", top, sub, cid, q, o, a, "Drill.", "understanding", "direct", sec3, ["campur_fisika_kimia"])
        )

write(sec3, pack3)

# Fix s3 main-09: wrong micro concept for radiasi - use same perpindahan_panas - OK

# ---------- Section 4 ----------
sec4 = "section-4/listrik-magnet-energi"
pack4 = {
    "authoring_request": {
        "mode": "foundation_micro",
        "subject": "ipa",
        "topic": "Listrik, Gelombang & Optik",
        "subtopic": "Rangkaian listrik",
        "grade_band": "sd_4_6_foundation",
        "student_goal": "Rangkaian seri-paralel, arus tertutup, magnet, transformasi energi (Section 4).",
        "requested_micro_concept_count": 3,
        "requested_main_questions_per_concept": 3,
        "requested_drill_questions_per_concept": 5,
        "language": "id",
    },
    "micro_concepts": [
        {
            "concept_id": "rangkaian_tertutup",
            "concept_name": "Arus pada rangkaian tertutup",
            "concept_description": "Arus mengalir jika lintasan tertutup dan sumber aktif.",
            "topic": "Listrik, Gelombang & Optik",
            "subtopic": "Rangkaian listrik",
            "target_error_tags": ["rangkaian_terbuka_salah", "sakelar_keliru"],
        },
        {
            "concept_id": "seri_vs_paralel",
            "concept_name": "Seri vs paralel (ciri dasar)",
            "concept_description": "Satu jalur vs banyak cabang; dampak satu lampu putus.",
            "topic": "Listrik, Gelombang & Optik",
            "subtopic": "Rangkaian listrik",
            "target_error_tags": ["campur_seri_paralel"],
        },
        {
            "concept_id": "transformasi_energi_listrik",
            "concept_name": "Transformasi energi listrik",
            "concept_description": "Listrik ke gerak, panas, cahaya, bunyi.",
            "topic": "Gerak, Gaya & Energi",
            "subtopic": "Energi & transformasi energi",
            "target_error_tags": ["salah_bentuk_energi_keluar"],
        },
    ],
    "main_questions": [
        main_item(
            "ipa-s4-main-01",
            "Listrik, Gelombang & Optik",
            "Rangkaian listrik",
            "rangkaian_tertutup",
            "Arus listrik pada rangkaian baterai–lampu mengalir jika ...",
            ["Rangkaian tertutup dan sumber terhubung benar", "Sakelor selalu terbuka", "Hanya satu kawat tanpa lampu", "Baterai tidak diperlukan"],
            0,
            "Lintasan tertutup untuk elektron.",
            "understanding",
            "concept_check",
            sec4,
            std_blocks("rangkaian tertutup"),
        ),
        main_item(
            "ipa-s4-main-02",
            "Listrik, Gelombang & Optik",
            "Rangkaian listrik",
            "rangkaian_tertutup",
            "Sakelar «off» berarti ...",
            ["Lintasan arus terputus (rangkaian terbuka)", "Arus makin besar", "Hambatan nol otomatis", "Tegangan hilang permanen dari baterai"],
            0,
            "Sakelor terbuka memutus jalur.",
            "understanding",
            "concept_check",
            sec4,
            std_blocks("sakelar"),
        ),
        main_item(
            "ipa-s4-main-03",
            "Listrik, Gelombang & Optik",
            "Rangkaian listrik",
            "rangkaian_tertutup",
            "Lampu tidak menyala padahal baterai baru: kemungkinan pertama yang dicek adalah ...",
            ["Kontak longgar atau rangkaian tidak tertutup", "Warna lampu", "Merek meja", "Suhu ruang saja"],
            0,
            "Cek kontinuitas rangkaian.",
            "application",
            "direct",
            sec4,
            std_blocks("troubleshoot"),
        ),
        main_item(
            "ipa-s4-main-04",
            "Listrik, Gelombang & Optik",
            "Rangkaian listrik",
            "seri_vs_paralel",
            "Pada rangkaian **seri** satu lampu putus, lampu lain pada jalur yang sama biasanya ...",
            ["Ikut padam karena satu jalur terputus", "Tetap menyala pasti", "Membesar arus tak terbatas", "Menyala lebih terang pasti"],
            0,
            "Seri: satu jalur.",
            "concept_understanding",
            "concept_check",
            sec4,
            std_blocks("seri"),
        ),
        main_item(
            "ipa-s4-main-05",
            "Listrik, Gelombang & Optik",
            "Rangkaian listrik",
            "seri_vs_paralel",
            "Pada rangkaian **paralel**, satu lampu putus, cabang lain yang sehat biasanya ...",
            ["Tetap bisa menyala", "Pasti semua padam", "Arus nol di semua cabang", "Tegangan baterai nol"],
            0,
            "Paralel: cabang independen.",
            "concept_understanding",
            "concept_check",
            sec4,
            std_blocks("paralel"),
        ),
        main_item(
            "ipa-s4-main-06",
            "Listrik, Gelombang & Optik",
            "Rangkaian listrik",
            "seri_vs_paralel",
            "Instalasi rumah banyak lampu agar independen: pola yang dipilih umumnya ...",
            ["Paralel", "Seri murni untuk semua", "Tanpa kawat", "Hanya satu sakelor global tanpa cabang"],
            0,
            "Paralel memungkinkan kontrol per titik.",
            "application",
            "direct",
            sec4,
            std_blocks("instalasi"),
        ),
        main_item(
            "ipa-s4-main-07",
            "Gerak, Gaya & Energi",
            "Energi & transformasi energi",
            "transformasi_energi_listrik",
            "Kipas angin yang menyala mengubah energi listrik menjadi ...",
            ["Energi gerak (kinetik kipas)", "Energi kimia pada baterai", "Energi potensial gravitasi murni", "Energi nuklir"],
            0,
            "Motor/listrik → gerak.",
            "understanding",
            "concept_check",
            sec4,
            std_blocks("kipas"),
        ),
        main_item(
            "ipa-s4-main-08",
            "Gerak, Gaya & Energi",
            "Energi & transformasi energi",
            "transformasi_energi_listrik",
            "Setrika listrik utama mengubah listrik menjadi ...",
            ["Panas", "Bunyi speaker", "Cahaya neon", "Gerak rotor besar"],
            0,
            "Elemen pemanas: listrik → panas.",
            "recall",
            "direct",
            sec4,
            std_blocks("setrika"),
        ),
        main_item(
            "ipa-s4-main-09",
            "Gerak, Gaya & Energi",
            "Energi & transformasi energi",
            "transformasi_energi_listrik",
            "Speaker yang berbunyi mengubah energi listrik menjadi ...",
            ["Energi bunyi", "Energi kimia baterai baru", "Energi potensial pegas saja", "Energi nuklir"],
            0,
            "Speaker: listrik → getaran bunyi.",
            "understanding",
            "concept_check",
            sec4,
            std_blocks("speaker"),
        ),
    ],
    "drill_questions": [],
}
d = 0
for cid, top, sub, pairs in [
    (
        "rangkaian_tertutup",
        "Listrik, Gelombang & Optik",
        "Rangkaian listrik",
        [
            ("Arus butuh jalur ...", ["Terbuka", "Tertutup", "Hampa vakum", "Tanpa sumber"], 1),
            ("Sakelor on berarti ...", ["Memutus", "Menghubungkan jalur", "Menghapus baterai", "Menambah massa"], 1),
            ("Lampu LED butuh ...", ["Rangkaian", "Hanya magnet", "Hanya gravitasi", "Tanpa tegangan"], 0),
            ("Kawat tembaga berfungsi sebagai ...", ["Penghantar", "Isolator murni", "Bahan bakar", "Pengurai"], 0),
            ("Baterai lemah sering membuat lampu ...", ["Lebih terang", "Redup atau padam", "Berubah warna meja", "Membesar massa"], 1),
        ],
    ),
    (
        "seri_vs_paralel",
        "Listrik, Gelombang & Optik",
        "Rangkaian listrik",
        [
            ("Seri: banyak lampu, satu jalur arus → putus satu ...", ["Semua bisa padam", "Tak terpengaruh", "Arus tak hingga", "Tegangan nol baterai"], 0),
            ("Paralel: cabang terpisah → satu putus ...", ["Semua pasti padam", "Cabang lain bisa hidup", "Hukum tidak berlaku", "Seri sama"], 1),
            ("Hias pohon natal sering rangkai lampu seri: jika satu putus ...", ["Semua sering padam", "Tak pernah padam", "Hanya baterai meledak", "Tak ada arus"], 0),
            ("Rumah: stop kontak cabang → pola ...", ["Seri saja", "Paralel", "Tanpa kawat", "Hanya AC"], 1),
            ("Pada paralel, tegangan cabang (model SD) cenderung ...", ["Sama dengan sumber", "Selalu nol", "Tak terdefinisi", "Hanya seri"], 0),
        ],
    ),
    (
        "transformasi_energi_listrik",
        "Gerak, Gaya & Energi",
        "Energi & transformasi energi",
        [
            ("Lampu pijar utama mengeluarkan ...", ["Hanya bunyi", "Cahaya dan panas", "Hanya massa", "Hanya magnet"], 1),
            ("Kutub magnet senama ...", ["Tolak", "Tarik", "Hilang", "Tidak ada gaya"], 0),
            ("Energi terbarukan contoh ...", ["Batu bara saja", "Angin & matahari", "Minyak saja", "Tak ada"], 1),
            ("Motor listrik → ...", ["Gerak", "Hanya panas", "Hanya bunyi", "Kimia dalam baterai"], 0),
            ("Setrika → energi keluar utama ...", ["Panas", "Bunyi", "Cahaya laser", "Gaya magnet"], 0),
        ],
    ),
]:
    for q, o, a in pairs:
        d += 1
        pack4["drill_questions"].append(
            drill_item(f"ipa-s4-drill-{d:02d}", top, sub, cid, q, o, a, "Drill.", "understanding", "direct", sec4, ["campur_seri_paralel"])
        )

write(sec4, pack4)

# ---------- Section 5 ----------
sec5 = "section-5/bumi-cuaca-sumber-daya"
pack5 = {
    "authoring_request": {
        "mode": "foundation_micro",
        "subject": "ipa",
        "topic": "Bumi & Alam Semesta",
        "subtopic": "Rotasi & revolusi bumi",
        "grade_band": "sd_4_6_foundation",
        "student_goal": "Rotasi–revolusi, siklus air, SDA, dampak lingkungan (Section 5 Study Guide).",
        "requested_micro_concept_count": 3,
        "requested_main_questions_per_concept": 3,
        "requested_drill_questions_per_concept": 5,
        "language": "id",
    },
    "micro_concepts": [
        {
            "concept_id": "rotasi_vs_revolusi",
            "concept_name": "Rotasi vs revolusi Bumi",
            "concept_description": "Siang-malam vs tahunan musim/rasi.",
            "topic": "Bumi & Alam Semesta",
            "subtopic": "Rotasi & revolusi bumi",
            "target_error_tags": ["menukar_rotasi_revolusi"],
        },
        {
            "concept_id": "siklus_air_ringkas",
            "concept_name": "Siklus air (tahapan utama)",
            "concept_description": "Evaporasi, kondensasi, presipitasi.",
            "topic": "Bumi & Alam Semesta",
            "subtopic": "Cuaca & iklim",
            "target_error_tags": ["urutan_siklus_salah"],
        },
        {
            "concept_id": "sumber_daya_alam_kelas",
            "concept_name": "SDA dan kelestarian sederhana",
            "concept_description": "Contoh SDA dan ide hemat.",
            "topic": "Bumi & Alam Semesta",
            "subtopic": "Sumber daya alam & kelestarian",
            "target_error_tags": ["sda_tidak_terbarukan_salah"],
        },
    ],
    "main_questions": [
        main_item(
            "ipa-s5-main-01",
            "Bumi & Alam Semesta",
            "Rotasi & revolusi bumi",
            "rotasi_vs_revolusi",
            "Siang dan bergantian malam disebabkan terutama oleh ...",
            ["Rotasi bumi pada porosnya", "Revolusi bumi mengelilingi matahari", "Gerhana bulan setiap hari", "Gempa tektonik"],
            0,
            "Rotasi ~24 jam → siang-malam.",
            "understanding",
            "concept_check",
            sec5,
            std_blocks("rotasi"),
        ),
        main_item(
            "ipa-s5-main-02",
            "Bumi & Alam Semesta",
            "Rotasi & revolusi bumi",
            "rotasi_vs_revolusi",
            "Periode revolusi bumi mengelilingi matahari kira-kira ...",
            ["Satu tahun", "Satu jam", "Satu menit", "Satu hari"],
            0,
            "Revolusi ~365 hari.",
            "recall",
            "direct",
            sec5,
            std_blocks("revolusi"),
        ),
        main_item(
            "ipa-s5-main-03",
            "Bumi & Alam Semesta",
            "Rotasi & revolusi bumi",
            "rotasi_vs_revolusi",
            "Musim di daerah berlatang sedang terkait erat dengan kemiringan sumbu dan ...",
            ["Revolusi serta posisi relatif terhadap matahari", "Hanya rotasi harian saja", "Hanya fase bulan", "Hanya pasang surut"],
            0,
            "Pola musiman tahunan berkaitan revolusi + kemiringan sumbu (model SD).",
            "concept_understanding",
            "concept_check",
            sec5,
            std_blocks("musim"),
        ),
        main_item(
            "ipa-s5-main-04",
            "Bumi & Alam Semesta",
            "Cuaca & iklim",
            "siklus_air_ringkas",
            "Uap air naik, membentuk awan, lalu jatuh sebagai hujan. Rangkaian ini melibatkan ...",
            ["Evaporasi/transpirasi, kondensasi, presipitasi", "Hanya fotosintesis", "Hanya rotasi inti bumi", "Hanya gaya magnet"],
            0,
            "Siklus air klasik.",
            "understanding",
            "concept_check",
            sec5,
            std_blocks("siklus air"),
        ),
        main_item(
            "ipa-s5-main-05",
            "Bumi & Alam Semesta",
            "Cuaca & iklim",
            "siklus_air_ringkas",
            "**Cuaca** berbeda dari **iklim** karena ...",
            [
                "Cuaca jangka pendek; iklim pola jangka panjang",
                "Cuaca sama dengan iklim",
                "Iklim hanya sejam",
                "Cuaca tidak bisa diukur"
            ],
            0,
            "Definisi skala waktu.",
            "concept_understanding",
            "concept_check",
            sec5,
            std_blocks("cuaca iklim"),
        ),
        main_item(
            "ipa-s5-main-06",
            "Bumi & Alam Semesta",
            "Cuaca & iklim",
            "siklus_air_ringkas",
            "Presipitasi mencakup ...",
            ["Hujan, salju, hujan es (air jatuh ke permukaan)", "Hanya angin kencang", "Hanya radiasi matahari", "Hanya gempa"],
            0,
            "Presipitasi = air turun dari atmosfer.",
            "recall",
            "direct",
            sec5,
            std_blocks("presipitasi"),
        ),
        main_item(
            "ipa-s5-main-07",
            "Bumi & Alam Semesta",
            "Sumber daya alam & kelestarian",
            "sumber_daya_alam_kelas",
            "Contoh **SDA terbarukan** yang dipakai untuk listrik adalah ...",
            ["Angin dan matahari (pembangkit)", "Batu bara murni tanpa batas", "Minyak bumi tak terbatas", "Tembaga bekas tanpa daur"],
            0,
            "Angin/surya dapat diperbarui aliran energinya.",
            "understanding",
            "concept_check",
            sec5,
            std_blocks("terbarukan"),
        ),
        main_item(
            "ipa-s5-main-08",
            "Bumi & Alam Semesta",
            "Sumber daya alam & kelestarian",
            "sumber_daya_alam_kelas",
            "Menghemat listrik di rumah berkontribusi pada ...",
            [
                "Mengurangi pemakaian energi dan dampak lingkungan terkait pembangkit",
                "Menambah polusi pasti",
                "Menghapus hukum termodinamika",
                "Menghilangkan gravitasi"
            ],
            0,
            "Hemat energi → kurang pembakaran/emisi (model sederhana).",
            "application",
            "direct",
            sec5,
            std_blocks("hemat"),
        ),
        main_item(
            "ipa-s5-main-09",
            "Bumi & Alam Semesta",
            "Sumber daya alam & kelestarian",
            "sumber_daya_alam_kelas",
            "Hutan sebagai sumber daya hayati perlu dikelola agar ...",
            [
                "Tetap berfungsi sebagai habitat dan penyangga iklim tanpa tebang liar",
                "Ditebang semua sekaligus",
                "Dibuat beton total",
                "Dihapus dari peta"
            ],
            0,
            "Pengelolaan berkelanjutan menjaga fungsi ekosistem.",
            "understanding",
            "concept_check",
            sec5,
            std_blocks("hutan"),
        ),
    ],
    "drill_questions": [],
}
d = 0
for cid, top, sub, pairs in [
    (
        "rotasi_vs_revolusi",
        "Bumi & Alam Semesta",
        "Rotasi & revolusi bumi",
        [
            ("Satu putaran bumi pada poros ≈ ...", ["365 hari", "24 jam", "1 jam", "1 tahun sidereal rasi saja"], 1),
            ("Revolusi mengubah posisi bumi relatif ...", ["Matahari", "Meja", "Sendok", "Buku saja"], 0),
            ("Gerhana melibatkan ...", ["Posisi benda langit", "Hanya rotasi meja", "Hanya warna cat", "Gaya gesek sepatu"], 0),
            ("Siang-malam dalam model modern terutama **bukan** disebabkan oleh ...", ["Rotasi bumi pada porosnya", "Hanya gerhana bulan setiap jam", "Bumi berputar dan cahaya matahari", "Perbedaan sisi bumi terhadap sumber cahaya"], 1),
            ("Tahun tropis/periode mengitari matahari ≈ ...", ["1 hari", "1 tahun", "1 detik", "1 menit"], 1),
        ],
    ),
    (
        "siklus_air_ringkas",
        "Bumi & Alam Semesta",
        "Cuaca & iklim",
        [
            ("Uap menjadi tetes awan: ...", ["Kondensasi", "Evaporasi", "Presipitasi langsung", "Erosi"], 0),
            ("Hujan turun: ...", ["Presipitasi", "Hanya evaporasi", "Hanya radiasi nuklir", "Konduksi logam"], 0),
            ("Iklim = ...", ["Cuaca 1 jam saja", "Pola rata-rata jangka panjang", "Kecepatan angin saat ini saja", "Nol"], 1),
            ("Sungai ke laut bagian dari ...", ["Siklus air", "Fotosintesis", "Listrik AC", "Magnet"], 0),
            ("Transpirasi berkaitan dengan ...", ["Uap dari tumbuhan", "Hanya es batu", "Hanya gempa", "Rotor listrik"], 0),
        ],
    ),
    (
        "sumber_daya_alam_kelas",
        "Bumi & Alam Semesta",
        "Sumber daya alam & kelestarian",
        [
            ("Air tawar termasuk ...", ["SDA", "Benda sintetis murni", "Planet", "Gelombang radio"], 0),
            ("Minyak bumi dianggap ...", ["Tak terbarukan skala manusia", "Selalu tak habis tanpa ekstraksi", "Bukan SDA", "Hanya energi kinetik"], 0),
            ("Reboisasi membantu ...", ["Mengurangi erosi dan menjaga air", "Menambah erosi", "Menghapus tanah", "Mematikan fotosintesis"], 0),
            ("Membuang sampah ke selokan dapat ...", ["Memperbaiki drainase", "Memperburuk banjir", "Menghilangkan hujan", "Menambah ozon"], 1),
            ("Panel surya memanfaatkan ...", ["Cahaya matahari", "Gaya gravitasi bulan", "Bunyi ultrasonik", "Hanya minyak"], 0),
        ],
    ),
]:
    for q, o, a in pairs:
        d += 1
        pack5["drill_questions"].append(
            drill_item(f"ipa-s5-drill-{d:02d}", top, sub, cid, q, o, a, "Drill.", "understanding", "direct", sec5, ["menukar_rotasi_revolusi"])
        )

write(sec5, pack5)

# ---------- Section 6 OSN ----------
sec6 = "section-6/pengayaan-osn-eksperimen-data"
pack6 = {
    "authoring_request": {
        "mode": "foundation_micro",
        "subject": "ipa",
        "topic": "Materi & Perubahannya",
        "subtopic": "Larutan & pemisahan campuran",
        "grade_band": "sd_4_6_foundation",
        "student_goal": "Membaca desain eksperimen dan inferensi kuantitatif sederhana (Section 6).",
        "requested_micro_concept_count": 3,
        "requested_main_questions_per_concept": 3,
        "requested_drill_questions_per_concept": 5,
        "language": "id",
    },
    "micro_concepts": [
        {
            "concept_id": "variabel_dari_tabel_osn",
            "concept_name": "Variabel dari skenario tabel",
            "concept_description": "Menyimpulkan variabel bebas/terikat dari deskripsi percobaan.",
            "topic": "Materi & Perubahannya",
            "subtopic": "Larutan & pemisahan campuran",
            "target_error_tags": ["salah_baca_tabel"],
        },
        {
            "concept_id": "proporsi_sederhana_data",
            "concept_name": "Perbandingan proporsi dari data",
            "concept_description": "Membandingkan rasio atau beda dua kelompok kecil.",
            "topic": "Materi & Perubahannya",
            "subtopic": "Larutan & pemisahan campuran",
            "target_error_tags": ["hitung_proporsi_salah"],
        },
        {
            "concept_id": "konsistensi_satuan_osn",
            "concept_name": "Konsistensi satuan",
            "concept_description": "Menolak kesimpulan yang melanggar satuan atau skala.",
            "topic": "Materi & Perubahannya",
            "subtopic": "Larutan & pemisahan campuran",
            "target_error_tags": ["satuan_tidak_konsisten"],
        },
    ],
    "main_questions": [
        main_item(
            "ipa-s6-main-01",
            "Materi & Perubahannya",
            "Larutan & pemisahan campuran",
            "variabel_dari_tabel_osn",
            "Percobaan mencatat «massa garam (g) tetap, volume air (mL) diubah, waktu larut (s) diukur». Variabel bebasnya adalah ...",
            ["Volume air", "Waktu larut", "Massa garam (jika dijaga tetap)", "Suhu ruang yang tidak disebut diubah"],
            0,
            "Yang diubah = volume air.",
            "experiment_interpretation",
            "experiment_interpretation",
            sec6,
            std_blocks("variabel tabel"),
        ),
        main_item(
            "ipa-s6-main-02",
            "Materi & Perubahannya",
            "Larutan & pemisahan campuran",
            "variabel_dari_tabel_osn",
            "Pada percobaan di atas, variabel terikatnya adalah ...",
            ["Waktu larut", "Volume air", "Merek gelas", "Warna meja"],
            0,
            "Terikat = yang diukur sebagai hasil.",
            "experiment_interpretation",
            "experiment_interpretation",
            sec6,
            std_blocks("terikat tabel"),
        ),
        main_item(
            "ipa-s6-main-03",
            "Materi & Perubahannya",
            "Larutan & pemisahan campuran",
            "variabel_dari_tabel_osn",
            "Agar percobaan di atas adil, massa garam dan pengadukan sebaiknya ...",
            ["Dijaga sama (kontrol)", "Diubah-ubah bebas", "Tidak dicatat", "Berbeda tiap detik tanpa aturan"],
            0,
            "Kontrol faktor pengganggu.",
            "experiment_interpretation",
            "experiment_interpretation",
            sec6,
            std_blocks("kontrol tabel"),
        ),
        main_item(
            "ipa-s6-main-04",
            "Materi & Perubahannya",
            "Larutan & pemisahan campuran",
            "proporsi_sederhana_data",
            "Data: 10 g gula larut dalam 50 mL air dingin 40 s; 10 g dalam 100 mL 20 s (model soal). Air lebih banyak cenderung ...",
            ["Mempercepat pelarutan pada contoh ini", "Selalu memperlambat tanpa syarat", "Tidak memengaruhi", "Menghilangkan gula"],
            0,
            "Pada angka contoh, volume lebih besar → waktu lebih pendek (lebih cepat).",
            "reasoning",
            "multi_step",
            sec6,
            std_blocks("proporsi"),
        ),
        main_item(
            "ipa-s6-main-05",
            "Materi & Perubahannya",
            "Larutan & pemisahan campuran",
            "proporsi_sederhana_data",
            "Jika massa tepung yang sama memberikan kekentalan lebih tinggi pada air lebih sedikit, berarti konsentrasi ...",
            ["Lebih tinggi pada air lebih sedikit", "Lebih rendah pada air lebih sedikit", "Tak bergantung volume", "Selalu nol"],
            0,
            "Konsentrasi massa per volume.",
            "reasoning",
            "multi_step",
            sec6,
            std_blocks("konsentrasi"),
        ),
        main_item(
            "ipa-s6-main-06",
            "Materi & Perubahannya",
            "Larutan & pemisahan campuran",
            "proporsi_sederhana_data",
            "Dua kelompok: A suhu 30°C waktu 12 s; B 40°C waktu 8 s (zat sama). Pola yang wajar ...",
            ["Lebih panas cenderung mempercepat (waktu lebih pendek)", "Lebih panas selalu memperlambat", "Suhu tidak berpengaruh", "Waktu harus sama"],
            0,
            "Pemanasan umumnya mempercepat pelarutan/difusi model SD.",
            "reasoning",
            "multi_step",
            sec6,
            std_blocks("suhu waktu"),
        ),
        main_item(
            "ipa-s6-main-07",
            "Materi & Perubahannya",
            "Larutan & pemisahan campuran",
            "konsistensi_satuan_osn",
            "Sebuah kesimpulan menyatakan «massa = 20 detik». Kesalahan utamanya adalah ...",
            ["Satuan tidak konsisten (massa vs waktu)", "Terlalu pendek", "Terlalu panjang", "Tidak ada kesalahan"],
            0,
            "Massa (g/kg) vs waktu (s) beda besaran.",
            "experiment_interpretation",
            "experiment_interpretation",
            sec6,
            std_blocks("satuan"),
        ),
        main_item(
            "ipa-s6-main-08",
            "Materi & Perubahannya",
            "Larutan & pemisahan campuran",
            "konsistensi_satuan_osn",
            "Grafik sumbu Y «volume (mL)» dan sumbu X «waktu (s)». Kemiringan garis menunjukkan ...",
            ["Laju perubahan volume terhadap waktu", "Massa dalam gram langsung", "Suhu dalam derajat jam", "Jumlah atom inti"],
            0,
            "Rasio perubahan volume per waktu.",
            "understanding",
            "data_interpretation",
            sec6,
            std_blocks("kemiringan"),
        ),
        main_item(
            "ipa-s6-main-09",
            "Materi & Perubahannya",
            "Larutan & pemisahan campuran",
            "konsistensi_satuan_osn",
            "Data ulangan percobaan tidak boleh dibuang seenaknya hanya karena ...",
            [
                "Tidak cocok selera tanpa alasan pengukuran/error",
                "Selalu harus dibuang jika beda",
                "Karena berbeda warna pena",
                "Karena berbeda hari Senin"
            ],
            0,
            "Data outlier ditinjau ulang metode, bukan sekadar preferensi.",
            "reasoning",
            "experiment_interpretation",
            sec6,
            std_blocks("etika data"),
        ),
    ],
    "drill_questions": [],
}
d = 0
for cid, top, sub, pairs in [
    (
        "variabel_dari_tabel_osn",
        "Materi & Perubahannya",
        "Larutan & pemisahan campuran",
        [
            ("Hasil pengukuran utama pada tabel percobaan biasanya dipasangkan dengan ...", ["Variabel terikat", "Merek sepatu", "Hari libur nasional", "Warna pensil"], 0),
            ("Faktor yang sengaja diubah peneliti disebut ...", ["Variabel bebas", "Variabel terikat", "Hipotesis akhir mutlak", "Kesimpulan tanpa data"], 0),
            ("Kontrol menjaga ...", ["Perbandingan adil", "Selalu membingungkan", "Tak perlu", "Menghapus data"], 0),
            ("Tabel tanpa satuan ...", ["Tetap ilmiah sempurna", "Berisiko ambigu", "Wajib benar", "Tak bisa salah"], 1),
            ("Hipotesis diuji lewat ...", ["Data percobaan", "Opini saja", "Warna saja", "Merek sepatu"], 0),
        ],
    ),
    (
        "proporsi_sederhana_data",
        "Materi & Perubahannya",
        "Larutan & pemisahan campuran",
        [
            ("Lebih banyak pelarut dengan massa zat sama → konsentrasi umumnya ...", ["Lebih tinggi", "Lebih rendah", "Tetap tak terdefinisi", "Nol"], 1),
            ("20 mL + 30 mL air (tetap suhu) total volume campuran ideal ...", ["50 mL", "600 mL", "10 mL", "0 mL"], 0),
            ("Jika waktu pelarutan turun saat suhu naik, hubungan sederhana ...", ["Suhu naik → lebih cepat", "Suhu naik → selalu lebih lambat", "Tak ada hubungan", "Suhu mematikan zat"], 0),
            ("Perbandingan dua rasio perlu ...", ["Satuan sama", "Satuan beda bebas", "Tanpa angka", "Tanpa konteks"], 0),
            ("10 detik vs 5 detik untuk proses yang sama → yang lebih cepat ...", ["5 detik", "10 detik", "Sama pasti", "Tak bisa ukur"], 0),
        ],
    ),
    (
        "konsistensi_satuan_osn",
        "Materi & Perubahannya",
        "Larutan & pemisahan campuran",
        [
            ("mL adalah ...", ["Volume", "Massa", "Suhu", "Kecepatan"], 0),
            ("g adalah ...", ["Massa", "Volume", "Detik", "Meter"], 0),
            ("°C untuk ...", ["Suhu", "Volume", "Massa jenis saja", "Arus listrik"], 0),
            ("Kesimpulan harus ...", ["Selaras satuan data", "Campur satuan seenaknya", "Tanpa angka", "Hanya gambar"], 0),
            ("Menulis «kecepatan = 10 kg» salah karena ...", ["kg bukan satuan kecepatan", "Benar selalu", "Tidak penting", "Hanya gaya"], 0),
        ],
    ),
]:
    for q, o, a in pairs:
        d += 1
        pack6["drill_questions"].append(
            drill_item(f"ipa-s6-drill-{d:02d}", top, sub, cid, q, o, a, "Drill.", "understanding", "direct", sec6, ["salah_baca_tabel"])
        )

write(sec6, pack6)
print("All IPA foundation micro packs written.")
